Mkdocs deplpoyment + styling
datajoint/element-calcium-imaging pull request #101
Opened 2022-11-09 21:31 UTC by CBroz1

2022-11-10 23:19 UTC, kabilar requested changes
Thanks @CBroz1.  Now that the initial docs pull request is merged, please pull from upstream.

2022-11-11 15:13 UTC, kabilar commented on docs/src/concepts.md
> ++ Neurolabware (we estimate 400 rigs in active use - TBC)
```suggestion
+ Sutter
+ Thorlabs
+ Bruker
+ Neurolabware
```

2022-11-11 15:23 UTC, kabilar requested changes
Thanks @CBroz1.  Minor comment above.

2022-11-12 00:06 UTC, CBroz1 commented
Thanks @kabilar - Resolved suggested change

2022-11-12 03:43 UTC, kabilar approved these changes

2022-11-12 03:43 UTC, merged