Bruker PrairieView import added to imaging
datajoint/element-calcium-imaging pull request #109
Opened 2022-12-13 20:30 UTC by kushalbakshi

2022-12-13 23:21 UTC, kabilar requested changes
Thanks @kushalbakshi.  Were you able to populate the PrairieView data through the entire schema?  I believe you will need to also update this list:

```
image_locators = {
    "NIS": get_nd2_files,
    "ScanImage": get_scan_image_files,
    "Scanbox": get_scan_box_files,
}
```

Please update:
- [x] version.py
- [x] changelog.md
- [ ] docs/src/concepts.md to specify that we now support PrairieView

2022-12-14 17:36 UTC, kushalbakshi commented
> Thanks @kushalbakshi. Were you able to populate the PrairieView data through the entire schema? I believe you will need to also update this list:
> 
> ```
> image_locators = {
>     "NIS": get_nd2_files,
>     "ScanImage": get_scan_image_files,
>     "Scanbox": get_scan_box_files,
> }
> ```
> 
> Please update:
> 
>     * [x]  version.py
> 
>     * [x]  changelog.md
> 
>     * [x]  docs/src/concepts.md to specify that we now support PrairieView

I only had enough data to populate an entry in the `ScanInfo` table. I now have datasets from both interested labs to try a full test

2022-12-15 00:10 UTC, kabilar commented on CHANGELOG.md
> ++ Update - Added file locator functions for Bruker PrairieView data.
```suggestion
## [0.5.1] - 2022-12-14
+ Add - File locator functions for Bruker PrairieView data. 
```

2022-12-15 00:10 UTC, kabilar commented on element_calcium_imaging/version.py
> +__version__ = "0.4.3"
```suggestion
__version__ = "0.5.1"
```

2022-12-15 00:13 UTC, kabilar commented on docs/src/concepts.md
> ++ Ingestion support for data acquired with ScanImage, Scanbox, Nikon NIS, and Bruker acquisition systems
```suggestion
+ Ingestion support for data acquired with ScanImage, Scanbox, Nikon NIS, and PrairieView acquisition systems
```

2022-12-15 00:21 UTC, kabilar commented on CHANGELOG.md
> ++ Update - Added file locator functions for Bruker PrairieView data.
Please add the following to the bottom of the file:
```
[0.5.1]: https://github.com/datajoint/element-calcium-imaging/releases/tag/0.5.1
```

2022-12-15 00:25 UTC, kabilar commented
Please pull from upstream to fast forward your branch.

2022-12-15 16:01 UTC, kabilar approved these changes
Thanks @kushalbakshi!

2022-12-15 16:01 UTC, merged