Notebook rendering and linting
datajoint/element-calcium-imaging pull request #120
Opened 2023-02-16 22:27 UTC by CBroz1

### Submission checklist

- [ ] Reviewed all `Files changed` prior to selecting `Create Pull Request`.
- [ ] Ran and passed all pytests, and ran the pipeline for features not covered by tests.
- [X] Ran pre-commit checks, including black, flake8, etc.
- [X] Updated the changelog and if making a new release, updated the version.py. **Proposing no new release**
- [X] Updated documentation, including concepts.md, tutorials.md, and relevant docstrings.
- [X] After merge, I will push a new tag to upstream (test* prefix if no new release).

### Submission details

In this pull request, I make the following changes:
- Concept: Why?
   - File: specifics
   - File: specifics

2023-02-20 19:45 UTC, CBroz1 commented
Hi @kabilar - If we're ready to move forward with this docs update without notebook 5, this PR is ready for review. I'll plan to address this notebook 5 issue after the dev container is in place

2023-02-20 21:44 UTC, kabilar commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://docs.datajoint.org/python/community/02-Contribute.html
```suggestion
    url: https://datajoint.com/docs/community/contribute/
```

2023-02-20 21:45 UTC, kabilar commented on docs/mkdocs.yaml
> +    - Workshop Demo: tutorials/2022-allen-institute-workshop.ipynb
```suggestion
```

2023-02-20 21:47 UTC, kabilar commented on docs/mkdocs.yaml
> +    - Workshop Demo: tutorials/2022-allen-institute-workshop.ipynb
Let's keep this notebook in the repo, but not render on the docs site.

2023-02-20 22:05 UTC, kabilar commented
The `cell_plot.py` and `widget.py` files are showing that all lines changed.  Is there any way to see a simpler diff of just the few lines that changed?

2023-02-20 22:49 UTC, kabilar commented
> That's odd. I'm seeing a relatively sparse diff, as shown below. Is that not what you see?
> 
> For these files, I sort imports via `isort` and add `-> output` typing suggestions to support API docs rendering. I make no functional changes.

Thanks.  Those changes look good.  For me it shows that all lines changed between the files.

2023-02-20 23:17 UTC, kabilar commented on docs/src/tutorials/index.md
> +[CodeBook](https://codebook.datajoint.io/). (Calcium Imaging notebooks coming soon!)
```suggestion
Our [YouTube tutorial](https://www.youtube.com/watch?v=gFLn0GB1L30) gives an overview of
the workflow files and notebooks, as well as core concepts related to calcium imaging
analysis. To try out the tutorial notebooks in an online Jupyter environment with access to
example data, visit
[CodeBook](https://codebook.datajoint.io/).
```

2023-02-20 23:20 UTC, kabilar commented on docs/src/tutorials/index.md
> +  all of the above for a workshop setting.
```suggestion
```

2023-02-20 23:23 UTC, kabilar commented on docs/src/tutorials/index.md
> +[CodeBook](https://codebook.datajoint.io/).
```suggestion
are also rendered as part of this site. To try out the notebooks in an online
Jupyter environment with access to example data, visit
[CodeBook](https://codebook.datajoint.io/).
```

2023-02-20 23:25 UTC, kabilar commented on docs/src/tutorials/index.md
> +  tables.
```suggestion
- [Workflow Structure](./02-workflow-structure-optional.ipynb) demonstrates the table
  architecture of the Element and key DataJoint basics for interacting with these
  tables.
```

2023-02-20 23:26 UTC, kabilar commented on docs/src/tutorials/index.md
> +  tools to download a sample model for trying out the Element.
```suggestion
- [Data Download](./00-data-download-optional.ipynb) highlights how to use DataJoint
  tools to download an example dataset to try out the Element.
```

2023-02-20 23:31 UTC, kabilar commented
Other than linting, are there other changes to `concepts.md`?  The diff is showing lots of changes so it is difficult to review.

2023-02-20 23:33 UTC, kabilar requested changes
Thanks @CBroz1!  A few suggestions above.

2023-02-21 15:06 UTC, CBroz1 commented
> Other than linting and spell checks, are there other changes to `concepts.md`? The diff is showing lots of changes so it is difficult to review.

@kabilar - Sorry, I could have broken up the hard wrapping into a separate commit for easier review. In `concepts`, I change the following:

- Hard wrap to 88
- `+` -> `-` for bulleted lists
- Add blank lines before and after headings and lists
- Set image as in-line text rather than bullet ([here](https://github.com/CBroz1/element-calcium-imaging/blame/main/docs/src/concepts.md#L130))
- Spelling corrections for `acquisition` and `performed`

2023-02-21 17:26 UTC, kabilar approved these changes
Thanks @CBroz1!

2023-02-21 17:27 UTC, merged